# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

policies:
  - type: commit
    spec:
      dco: true
      gpg:
        required: true
        identity:
          gitHubOrganization: janderssonse
      spellcheck:
        locale: US
      maximumOfOneCommit: true
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: true
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - release
        scopes:
          - .*
