// SPDX-FileCopyrightText: Josef Andersson
//
// SPDX-License-Identifier: CC0-1.0
= Gommitlint
:revdate: {docdatetime}
:doctype: article
:imagesdir: assets
:source-highlighter: rouge
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
image:https://img.shields.io/github/v/tag/itiquette/gommitlint?style=for-the-badge&color=yellow[Tag,link=https://github.com/itiquette/gommitlint/tags]
https://scorecard.dev/viewer/?uri=github.com/itiquette/gommitlint[image:https://api.scorecard.dev/projects/github.com/itiquette/gommitlint/badge?style=for-the-badge[OpenSSF Scorecard]]
link:LICENSE[image:https://img.shields.io/badge/License-EUPL%201.2-blue?style=for-the-badge[EUPL 1.2]]
image:https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fapi.reuse.software%2Fstatus%2Fgithub.com%2Fitiquette%2Fgommitlint&query=status&style=for-the-badge&label=REUSE[REUSE,link=https://api.reuse.software/info/github.com/itiquette/gommitlint]

== What can this tool do for you?
*Gommitlint* is a simple CLI-tool for validating Git commit messages and repository state.
At the moment it is in early development.

== Where can you use it?

* As a CLI-tool for pre-commit validation
* In a CI/CD-pipeline to enforce team standards
* As a Git hook for automatic validation

=== Available validation rules:

TE
==== Commit Message Rules

* *CommitsAhead* - Limits how far a branch can diverge from a reference branch
* *ConventionalCommit* - Enforces https://www.conventionalcommits.org[Conventional Commits] format with configurable types and scopes
* *ImperativeVerb* - Validates that commit messages begin with a verb in the imperative mood
* *JiraReference* - Verifies commits reference valid Jira issue keys in a consistent format
* *SubjectCase* - Enforces consistent capitalization in commit subjects
* *SubjectSuffix* - Prevents commit subjects from ending with specified characters
* *SubjectLength* - Limits commit subject line length for readability (default: 100 chars)
* *SignOff* - Ensures commits include a Developer Certificate of Origin sign-off line
* *Spell* - Catches common spelling mistakes with locale-specific dictionaries
* *Signature* - Verifies commits have a cryptographic signature (GPG or SSH)
* *SignedIdentity* - Validates signatures against trusted keys with full cryptographic verification

== Getting Started
TODO
//1. Check out the link:docs/usage.adoc[Usage Guide] for a quick start.
// 2. The link:INSTALL.adoc[Installation Guide] will get you up and running.

== Make Gommitlint better?
ED: Currently I'm not reading PRs as there are a few base things to fix before that.

Here's how you can contribute:

* Found a bug or have a great idea? Let us know in our https://github.com/itiquette/gommitlint/issues[Issue Tracker]
* Want to contribute code? Check out our link:CONTRIBUTING.md[Contribution Guide] to get started.

== For developers
TODO
//If you're interested in how it works, see the link:DEVELOPMENT.adoc[Development Guide].

== What's next?
Check out our https://github.com/itiquette/gommitlint/issues[Issues page].

== A friendly reminder
**Please Note**: Gommitlint is currently in Alpha. This means:

* APIs might change in breaking ways
* Documentation is still being developed
* Feel free to share ideas on how we can make it better

== Credits & History

Gommitlint was inspired by Sidero Labs https://github.com/siderolabs/conform[Conform tool].

== Legal Stuff
Gommitlint is licensed under the EUPL 1.2 License.
Most of the non-code bits are under Creative Commons CC0-1.0.
For all the details, check out our link:LICENSE[LICENSE] file and the headers in each file.
