# SPDX-FileCopyrightText: 2025 itiquette/gommitlint <https://github.com/itiquette/gommitlint>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
  ".github/pull_request_template.md",
  "go.sum",
  "docs/dco.txt",
  "renovate.json",
  "**/*/valid.priv",
  "**/*/valid.pub",
  ".gitleaksignore",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "SPDX-FileCopyrightText: 2025 itiquette/gommitlint <https://github.com/itiquette/gommitlint>"
SPDX-License-Identifier = "CC0-1.0"
