# SPDX-FileCopyrightText: Josef Andersson
#
# SPDX-License-Identifier: CC0-1.0

---
name: Gommitlint Workflow

on:
  push:
    branches:
      - main
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  # commitlint:
  #   permissions:
  #     contents: read
  #   uses: ./.github/workflows/commitlint.yml
  dependencyreviewlint:
    permissions:
      contents: read
    uses: ./.github/workflows/dependencyreview.yml
  licenselint:
    permissions:
      contents: read
    uses: ./.github/workflows/licenselint.yml
  golint:
    permissions:
      contents: read
    uses: ./.github/workflows/golint.yml
  misclint:
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/misclint.yml
  test:
    permissions:
      contents: read
    if: ${{ !failure() }}
    needs: [licenselint, dependencyreviewlint, golint, misclint]
    #    needs: [licenselint, commitlint, dependencyreviewlint, golint, misclint]
    uses: ./.github/workflows/test.yml
